=== 52North/UncertWeb/uts/STAS/trunk/STAS/src/main/xsd/parameter/parameter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uncertweb.org/sta/wps/parameter" xmlns:par="http://www.uncertweb.org/sta/wps/parameter"
	elementFormDefault="qualified">
	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" name="parameter">
					<xs:complexType>
						<xs:attribute name="key" type="xs:string" use="required" />
						<xs:attribute name="value" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 52North/UncertWeb/uts/STAS/trunk/STAS/src/main/xsd/parameter/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<par:parameters xmlns:par="http://www.uncertweb.org/sta/wps/parameter"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uncertweb.org/sta/wps/parameter parameter.xsd ">
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
	<par:parameter key="adsf" value="sadfasdf" />
</par:parameters>
